import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Loader as Loader2, Zap, Eye, Send, Check } from 'lucide-react'
import { useSessions } from '../hooks/useSessions'
import NavRail from '../components/NavRail'
import { useToast } from '../context/ToastContext'

export default function AddSessionPage() {
  const { igUsername } = useParams(); const { generateSession } = useSessions(igUsername); const navigate = useNavigate(); const { toast } = useToast()
  const [name, setName] = useState(''); const [level, setLevel] = useState('read'); const [generating, setGenerating] = useState(false)
  const handleGenerate = async (e) => { e.preventDefault(); if (!name.trim()) return; setGenerating(true); const result = await generateSession(name.trim(), level); setGenerating(false); if (result) { toast('Wingman link generated', 'success'); navigate(`/sessions/${igUsername}`) } }
  return <div className="min-h-screen flex bg-background text-foreground font-sans"><NavRail activePage="sessions" /><main className="fluid-page min-w-0 flex-1 pb-20 md:pb-0"><div className="fluid-content max-w-2xl py-[clamp(1.5rem,5vw,2.5rem)]"><Link to={`/sessions/${igUsername}`} className="mb-8 inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft size={17} /> Back to wingmen</Link><div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary">New access link</p><h1 className="text-3xl font-semibold tracking-tight">Add a wingman</h1><p className="mt-2 text-sm text-muted-foreground">Create a private link for someone you trust to help with @{igUsername}.</p></div><form onSubmit={handleGenerate} className="rounded-2xl border bg-card p-5 shadow-sm md:p-7"><div className="mb-7 flex items-center gap-3 rounded-xl bg-accent p-4"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Zap size={19} /></div><div><p className="text-sm font-semibold">Secure, revocable access</p><p className="text-xs text-muted-foreground">You can change or revoke this link later.</p></div></div><label className="mb-2 block text-sm font-medium">Wingman name</label><input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Alex or Social team" className="mb-7 w-full rounded-xl border bg-background px-3.5 py-3 text-sm outline-none ring-primary/20 transition focus:ring-4" /><label className="mb-2 block text-sm font-medium">Access level</label><div className="mb-8 grid gap-3 sm:grid-cols-2"><AccessOption active={level === 'read'} onClick={() => setLevel('read')} icon={Eye} title="Read only" copy="View conversations without sending replies." /><AccessOption active={level === 'send'} onClick={() => setLevel('send')} icon={Send} title="Read & reply" copy="View messages and send replies for you." /></div><button type="submit" disabled={generating || !name.trim()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3 text-sm font-semibold text-primary-foreground shadow-sm hover:opacity-90 disabled:opacity-50">{generating ? <><Loader2 size={16} className="animate-spin" /> Generating link…</> : <><Check size={16} /> Generate wingman link</>}</button></form></div></main></div>
}
function AccessOption({ active, onClick, icon: Icon, title, copy }) { return <button type="button" onClick={onClick} className={`flex items-start gap-3 rounded-xl border p-4 text-left transition ${active ? 'border-primary bg-accent ring-2 ring-primary/10' : 'hover:bg-muted'}`}><Icon size={19} className={active ? 'text-primary' : 'text-muted-foreground'} /><span><span className="block text-sm font-semibold">{title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{copy}</span></span></button> }
